version: '3.2'
services:
  webapi:
    build: ./WebApi
    image: dedegor/webapi:latest
    ports:
      - "5178:80"  
  vite-project:
    build: ./ClientApp
    image: dedegor/clientapp:latest
    ports:
      - "80:80"